name: Security

on:
  schedule:
  - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  osv-scan:
    permissions:
      security-events: write
    name: osv-scan
    runs-on: ubuntu-latest
    steps:
      - name: "OSV scanner"
        uses: google/osv-scanner-action/osv-scanner-action@v2.0.2
        with:
          scan-args: |
            --lockfile=app/gradle.lockfile
            --output=osv.sarif
            --format=sarif
        continue-on-error: true
